#!/bin/bash

# deletes recursively temporary files
# part of shell-tools (GPLv3)

if [[ "$1" ]] ; then
	folder="$1"
else
	folder=$(pwd)
fi

# maybe we can combine this with find
echo 'DELETE: \n';ls "$folder"/*~;

find . -name "$folder"/'*~' -type f -exec rm  {} \;
